
Vagrant.configure("2") do |config|
    config.vm.box = "centos-7.2"
    config.vm.network "private_network", ip: "192.168.3.3"
    config.vbguest.auto_update = false
            cfg.vm.synced_folder "E:\\ehlxr\\Vagrant", "/vagrant"
    # 自定义初始化执行脚本
    config.vm.provision "shell", path: "../config/init.sh"

    # 默认 root 登陆
    config.ssh.username = "root"
    config.ssh.password = "vagrant"
    config.ssh.insert_key = "true"
end